
spring:
  datasource:
    initialization-mode: always
    username: synapse
    password: ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
    url: jdbc:postgresql://127.0.0.1:5432/synapse
  jpa:
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson
  eventhandling:
    processors:
      logging:
        mode: subscribing

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus